version: '2'
services:
    jhipstertestapp-app:
        image: jhipstertestapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://jhipstertestapp-mariadb:3306/jhipstertestapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 1214:1214
    jhipstertestapp-mariadb:
        extends:
            file: mariadb.yml
            service: jhipstertestapp-mariadb
